package zerobouncego

var MOCK_VALIDATE_RESPONSE = map[string]string{
	"disposable@example.com": `{
		"address": "disposable@example.com",
		"status": "do_not_mail",
		"sub_status": "disposable",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:27.816"
	}`,
	"invalid@example.com": `{
		"address": "invalid@example.com",
		"status": "invalid",
		"sub_status": "mailbox_not_found",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:28.003"
	}`,
	"valid@example.com": `{
		"address": "valid@example.com",
		"status": "valid",
		"sub_status": "",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:28.105"
	}`,
	"toxic@example.com": `{
		"address": "toxic@example.com",
		"status": "do_not_mail",
		"sub_status": "toxic",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:28.210"
	}`,
	"donotmail@example.com": `{
		"address": "donotmail@example.com",
		"status": "do_not_mail",
		"sub_status": "role_based",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:28.329"
	}`,
	"spamtrap@example.com": `{
		"address": "spamtrap@example.com",
		"status": "spamtrap",
		"sub_status": "",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:28.380"
	}`,
	"abuse@example.com": `{
		"address": "abuse@example.com",
		"status": "abuse",
		"sub_status": "",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:28.585"
	}`,
	"catch_all@example.com": `{
		"address": "catch_all@example.com",
		"status": "catch-all",
		"sub_status": "",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:28.639"
	}`,
	"antispam_system@example.com": `{
		"address": "antispam_system@example.com",
		"status": "unknown",
		"sub_status": "antispam_system",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:28.767"
	}`,
	"does_not_accept_mail@example.com": `{
		"address": "does_not_accept_mail@example.com",
		"status": "invalid",
		"sub_status": "does_not_accept_mail",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:28.929"
	}`,
	"exception_occurred@example.com": `{
		"address": "exception_occurred@example.com",
		"status": "unknown",
		"sub_status": "exception_occurred",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:28.971"
	}`,
	"failed_smtp_connection@example.com": `{
		"address": "failed_smtp_connection@example.com",
		"status": "unknown",
		"sub_status": "failed_smtp_connection",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:29.144"
	}`,
	"failed_syntax_check@example.com": `{
		"address": "failed_syntax_check@example.com",
		"status": "invalid",
		"sub_status": "failed_syntax_check",
		"free_email": false,
		"did_you_mean": null,
		"account": "",
		"domain": "",
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:29.312"
	}`,
	"forcible_disconnect@example.com": `{
		"address": "forcible_disconnect@example.com",
		"status": "unknown",
		"sub_status": "forcible_disconnect",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:29.932"
	}`,
	"global_suppression@example.com": `{
		"address": "global_suppression@example.com",
		"status": "do_not_mail",
		"sub_status": "global_suppression",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:30.208"
	}`,
	"greylisted@example.com": `{
		"address": "greylisted@example.com",
		"status": "unknown",
		"sub_status": "greylisted",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:30.502"
	}`,
	"leading_period_removed@example.com": `{
		"address": "leading_period_removed@example.com",
		"status": "valid",
		"sub_status": "leading_period_removed",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:30.742"
	}`,
	"mail_server_did_not_respond@example.com": `{
		"address": "mail_server_did_not_respond@example.com",
		"status": "unknown",
		"sub_status": "mail_server_did_not_respond",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:30.854"
	}`,
	"mail_server_temporary_error@example.com": `{
		"address": "mail_server_temporary_error@example.com",
		"status": "unknown",
		"sub_status": "mail_server_temporary_error",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:30.913"
	}`,
	"mailbox_quota_exceeded@example.com": `{
		"address": "mailbox_quota_exceeded@example.com",
		"status": "invalid",
		"sub_status": "mailbox_quota_exceeded",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:31.084"
	}`,
	"mailbox_not_found@example.com": `{
		"address": "mailbox_not_found@example.com",
		"status": "invalid",
		"sub_status": "mailbox_not_found",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:31.153"
	}`,
	"no_dns_entries@example.com": `{
		"address": "no_dns_entries@example.com",
		"status": "invalid",
		"sub_status": "no_dns_entries",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:31.225"
	}`,
	"possible_trap@example.com": `{
		"address": "possible_trap@example.com",
		"status": "do_not_mail",
		"sub_status": "possible_trap",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:31.453"
	}`,
	"possible_typo@example.com": `{
		"address": "possible_typo@example.com",
		"status": "invalid",
		"sub_status": "possible_typo",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:31.537"
	}`,
	"role_based@example.com": `{
		"address": "role_based@example.com",
		"status": "do_not_mail",
		"sub_status": "role_based",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:31.679"
	}`,
	"timeout_exceeded@example.com": `{
		"address": "timeout_exceeded@example.com",
		"status": "unknown",
		"sub_status": "timeout_exceeded",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:31.810"
	}`,
	"unroutable_ip_address@example.com": `{
		"address": "unroutable_ip_address@example.com",
		"status": "invalid",
		"sub_status": "unroutable_ip_address",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:32.040"
	}`,
	"free_email@example.com": `{
		"address": "free_email@example.com",
		"status": "valid",
		"sub_status": "",
		"free_email": true,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:32.095"
	}`,
	"role_based_catch_all@example.com": `{
		"address": "role_based_catch_all@example.com",
		"status": "do_not_mail",
		"sub_status": "role_based_catch_all",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:32.251"
	}`,
	"unknown@example.com": `{
		"address": "unknown@example.com",
		"status": "unknown",
		"sub_status": "mail_server_temporary_error",
		"free_email": false,
		"did_you_mean": null,
		"account": null,
		"domain": null,
		"domain_age_days": "9692",
		"smtp_provider": "example",
		"mx_found": "true",
		"mx_record": "mx.example.com",
		"firstname": "zero",
		"lastname": "bounce",
		"gender": "male",
		"country": "United States",
		"region": "Florida",
		"city": "West Palm Beach",
		"zipcode": "33401",
		"processed_at": "2023-03-23 12:30:31.961"
	}`,
}
